stages:
    get_data:
        cmd: dvc pull data_processed.csv
        outs:
            - data_processed.csv
    train:
        cmd: python train.py
        deps:
            - train.py
            - data_processed.csv
        outs:
            - by_region.png
        metrics:
            - metrics.json:
                  cache: false
